---
apiVersion: v1
kind: Pod
metadata:
  name: rw-benchmark-docker
  labels:
    app: rw-benchmark-docker
spec:
  restartPolicy: Never
  containers:
    - name: test
      command:
        - python
        - /app/write_data.py
        - "--test-path"
        - "/test-volume/data"
        - "4096"
      volumeMounts:
        - name: test-volume
          mountPath: /test-volume
      image: evanfoster/kata-virtiofs-naive-rw-benchmark
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 4
          memory: 4Gi
  dnsPolicy: Default
  volumes:
    - name: test-volume
      emptyDir: {}
